version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64 # M1でも動作するように
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
      - ./pyproject.toml:/app/pyproject.toml
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
